// Array of common university departments
const departments = [
    "Computer Science",
    "Engineering",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Geography",
    "History",
    "Economics",
    "Sociology",
    "Psychology",
    "Political Science",
    "Business Administration",
    "Fine Arts",
    "Linguistics"
];

const departmentSubjects = {
    "Computer Science": [
        "Data Structures",
        "Operating Systems",
        "Computer Networks",
        "Database Systems",
        "Artificial Intelligence",
        "Machine Learning",
        "Software Engineering",
        "Cybersecurity",
        "Web Development",
        "Mobile Development",
        "Cloud Computing",
        "Theory of Computation",
        "Compiler Design",
        "Computer Graphics",
        "Distributed Systems"
    ],
    "Engineering": [
        "Thermodynamics",
        "Fluid Mechanics",
        "Structural Analysis",
        "Electrical Circuits",
        "Control Systems",
        "Materials Science",
        "Manufacturing Processes",
        "Engineering Design",
        "Project Management",
        "Statics",
        "Dynamics",
        "Heat Transfer",
        "Instrumentation",
        "Renewable Energy",
        "Aerodynamics"
    ],
    "Mathematics": [
        "Calculus I",
        "Calculus II",
        "Linear Algebra",
        "Differential Equations",
        "Abstract Algebra",
        "Real Analysis",
        "Complex Analysis",
        "Probability",
        "Statistics",
        "Discrete Mathematics",
        "Number Theory",
        "Geometry",
        "Topology",
        "Mathematical Logic",
        "Numerical Analysis"
    ],
    "Physics": [
        "Classical Mechanics",
        "Electromagnetism",
        "Optics",
        "Thermodynamics",
        "Quantum Mechanics",
        "Relativity",
        "Solid State Physics",
        "Nuclear Physics",
        "Particle Physics",
        "Astrophysics",
        "Computational Physics",
        "Experimental Physics",
        "Mathematical Methods in Physics",
        "Electronics",
        "Plasma Physics"
    ],
    "Chemistry": [
        "General Chemistry",
        "Organic Chemistry",
        "Inorganic Chemistry",
        "Physical Chemistry",
        "Analytical Chemistry",
        "Biochemistry",
        "Polymer Chemistry",
        "Environmental Chemistry",
        "Medicinal Chemistry",
        "Theoretical Chemistry",
        "Spectroscopy",
        "Crystallography",
        "Chemical Kinetics",
        "Chemical Thermodynamics",
        "Electrochemistry"
    ],
    "Biology": [
        "General Biology",
        "Cell Biology",
        "Molecular Biology",
        "Genetics",
        "Ecology",
        "Evolutionary Biology",
        "Physiology",
        "Anatomy",
        "Microbiology",
        "Botany",
        "Zoology",
        "Developmental Biology",
        "Immunology",
        "Neurobiology",
        "Biochemistry"
    ],
    "Geography": [
        "Physical Geography",
        "Human Geography",
        "Cartography",
        "Geographic Information Systems (GIS)",
        "Remote Sensing",
        "Economic Geography",
        "Urban Geography",
        "Regional Geography",
        "Environmental Geography",
        "Geomorphology",
        "Climatology",
        "Hydrology",
        "Biogeography",
        "Population Geography",
        "Political Geography"
    ],
    "History": [
        "Ancient History",
        "Medieval History",
        "Modern History",
        "World History",
        "Cultural History",
        "Social History",
        "Political History",
        "Economic History",
        "Military History",
        "Intellectual History",
        "Historiography",
        "Archaeology",
        "Diplomatic History",
        "Gender History",
        "Religious History"
    ],
    "Economics": [
        "Microeconomics",
        "Macroeconomics",
        "Econometrics",
        "International Economics",
        "Development Economics",
        "Labor Economics",
        "Public Finance",
        "Monetary Economics",
        "Financial Economics",
        "Industrial Organization",
        "Game Theory",
        "Behavioral Economics",
        "Environmental Economics",
        "Health Economics",
        "Urban Economics"
    ],
    "Sociology": [
        "Social Theory",
        "Research Methods",
        "Social Inequality",
        "Deviance and Crime",
        "Family and Kinship",
        "Urban Sociology",
        "Rural Sociology",
        "Political Sociology",
        "Medical Sociology",
        "Educational Sociology",
        "Gender Studies",
        "Race and Ethnicity",
        "Globalization",
        "Social Psychology",
        "Criminology"
    ],
    "Psychology": [
        "Cognitive Psychology",
        "Developmental Psychology",
        "Social Psychology",
        "Clinical Psychology",
        "Neuropsychology",
        "Counseling Psychology",
        "Educational Psychology",
        "Industrial-Organizational Psychology",
        "Health Psychology",
        "Forensic Psychology",
        "Comparative Psychology",
        "Cultural Psychology",
        "Evolutionary Psychology",
        "Personality Psychology",
        "Behavioral Neuroscience"
    ],
    "Political Science": [
        "Political Theory",
        "Comparative Politics",
        "International Relations",
        "Public Administration",
        "Political Methodology",
        "American Politics",
        "European Politics",
        "Asian Politics",
        "African Politics",
        "Latin American Politics",
        "Political Economy",
        "Public Policy",
        "Constitutional Law",
        "Human Rights",
        "Geopolitics"
    ],
    "Business Administration": [
        "Management Principles",
        "Marketing Management",
        "Financial Accounting",
        "Organizational Behavior",
        "Operations Management",
        "Strategic Management",
        "Human Resource Management",
        "Business Law",
        "Entrepreneurship",
        "International Business",
        "Business Ethics",
        "Management Information Systems",
        "Supply Chain Management",
        "Project Management",
        "Business Analytics"
    ],
    "Fine Arts": [
        "Art History",
        "Painting",
        "Sculpture",
        "Drawing",
        "Photography",
        "Printmaking",
        "Ceramics",
        "Textile Arts",
        "Digital Art",
        "Performance Art",
        "Installation Art",
        "Graphic Design",
        "Industrial Design",
        "Fashion Design",
        "Interior Design"
    ],
    "Linguistics": [
        "Phonetics",
        "Phonology",
        "Morphology",
        "Syntax",
        "Semantics",
        "Pragmatics",
        "Historical Linguistics",
        "Sociolinguistics",
        "Psycholinguistics",
        "Computational Linguistics",
        "Neurolinguistics",
        "Applied Linguistics",
        "Descriptive Linguistics",
        "Theoretical Linguistics",
        "Cognitive Linguistics"
    ]
};

const particulars = [
    "Introduction to",
    "Advanced",
    "Society and",
    "Optimal",
    "Research for",
    "Accounting in",
    "Academic Writing in",
    "Principles of",
    "Fundamentals of",
    "Theories of"
];

module.exports = {
    departments,
    departmentSubjects,
    particulars
}