INSERT INTO Lecturer (LecId, LecFirstName, LecLastName, Department, UserId) VALUES
(1, 'Maymie', 'Lemke', 'History', 0),
(2, 'Concepcion', 'Casper', 'Linguistics', 1),
(3, 'Jedediah', 'Sporer', 'Linguistics', 2),
(4, 'Deborah', 'Kassulke-Brekke', 'Linguistics', 3),
(5, 'Kristian', 'Herzog-Smitham', 'Business Administration', 4),
(6, 'Kristian', 'Dickinson', 'Engineering', 5),
(7, 'Gregory', 'Stokes', 'Political Science', 6),
(8, 'Justus', 'Sanford-Mraz', 'Economics', 7),
(9, 'Jerome', 'Grimes', 'Computer Science', 8),
(10, 'Blaise', 'Wiegand', 'Psychology', 9),
(11, 'Jamal', 'Schmidt', 'Computer Science', 10),
(12, 'Antonietta', 'King-Stoltenberg', 'Political Science', 11),
(13, 'Orie', 'Little', 'Sociology', 12),
(14, 'Gerry', 'Boyle', 'Business Administration', 13),
(15, 'Iva', 'Bins', 'Biology', 14),
(16, 'Selmer', 'Kuphal', 'Fine Arts', 15),
(17, 'Madilyn', 'Herman', 'Chemistry', 16),
(18, 'Llewellyn', 'Hand-Stokes', 'Geography', 17),
(19, 'Trace', 'Hand', 'Fine Arts', 18),
(20, 'Greg', 'Muller', 'Economics', 19),
(21, 'Susana', 'Greenholt', 'Psychology', 20),
(22, 'Collin', 'Hilpert', 'History', 21),
(23, 'Felicity', 'Cruickshank', 'Geography', 22),
(24, 'Nakia', 'Hilpert', 'Economics', 23),
(25, 'Jewell', 'Reichel', 'Fine Arts', 24),
(26, 'Magnus', 'Dach', 'Engineering', 25),
(27, 'Angelo', 'Erdman', 'Psychology', 26),
(28, 'Gerard', 'O''Conner', 'History', 27),
(29, 'Linnea', 'Daugherty', 'History', 28),
(30, 'Arturo', 'Wolf', 'Psychology', 29),
(31, 'Micah', 'Langworth', 'Geography', 30),
(32, 'Shane', 'Bogan', 'Engineering', 31),
(33, 'Elizabeth', 'Wisoky', 'Business Administration', 32),
(34, 'Deshawn', 'Champlin', 'Fine Arts', 33),
(35, 'Armand', 'Collier', 'Mathematics', 34),
(36, 'Ashton', 'Cummerata', 'Linguistics', 35),
(37, 'Raphaelle', 'Lesch', 'Sociology', 36),
(38, 'Ferne', 'Torphy', 'Linguistics', 37),
(39, 'Arne', 'Sauer', 'Geography', 38),
(40, 'Clifford', 'Kris', 'Psychology', 39);

